version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: 8:00
      timezone: Europe/London
    open-pull-requests-limit: 10
    allow:
      - dependency-type: all
