require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  EnabledByDefault: true
  Exclude:
    - "vendor/bundle/**/*" # External libraries

Bundler/GemComment: # Prefer inline comments
  Enabled: false

Layout/LineLength:
  Max: 100 # Default is 80 which is a bit narrow

Layout/MultilineAssignmentLayout: # Prefer same line
  EnforcedStyle: same_line

Metrics/BlockLength:
  Exclude:
    - "spec/**/*" # OK for specs to have large blocks

Style/Documentation: # Not a public library so not needed
  Enabled: false

Style/DocumentationMethod: # Not a public library so not needed
  Enabled: false

Style/Copyright: # Not needed in every file
  Enabled: false

Style/FrozenStringLiteralComment: # Remove in ruby 3
  Enabled: false

Style/InlineComment: # Good in lots of cases
  Enabled: false

Style/IpAddresses:
  Exclude:
    - "spec/**/*" # Good for tests

Style/MethodCallWithArgsParentheses: # Not standard ruby style
  Enabled: false

Style/MissingElse: # Useful in some cases
  Enabled: false
