require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  EnabledByDefault: true
  Exclude:
    - "vendor/bundle/**/*" # External libraries

Layout/MultilineAssignmentLayout: # Prefer same line
  EnforcedStyle: same_line

Lint/ConstantResolution: # Not standard ruby style
  Enabled: false

Style/Documentation: # Not a public library so not needed
  Enabled: false

Style/DocumentationMethod: # Not a public library so not needed
  Enabled: false

Style/Copyright: # Not needed in every file
  Enabled: false

Style/FrozenStringLiteralComment: # Remove in ruby 3
  Enabled: false

Style/InlineComment: # Good in lots of cases
  Enabled: false

Style/MethodCallWithArgsParentheses: # Not standard ruby style
  Enabled: false

Style/MissingElse: # Useful in some cases
  Enabled: false
