name: CI

on:
  push:
    branches: [master]
  pull_request:

env:
  RUBY_VERSION: 3.0.0

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: gems-${{ hashFiles('.ruby-version') }}-${{ hashFiles('Gemfile.lock') }}
          restore-keys: gems-${{ hashFiles('.ruby-version') }}-

      - run: ./bin/setup

      - run: ./bin/test

      - run: ./bin/quality

      - run: ./bin/run

      - run: ./bin/git_changes

  automerge:
    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'

    needs: [test]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@0.2.0
        with:
          script: |
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
          github-token: ${{github.token}}
